from typing import Literal
from pydantic import BaseModel, Field
from schemas.enums import PassHeight, Bodypart

class InferenceRequest(BaseModel):
    start_x: float = Field(..., example=60.0)
    start_y: float = Field(..., example=40.0)
    end_x: float = Field(..., example=78.0)
    end_y: float = Field(..., example=35.0)
    length: float = Field(..., example=22.5)
    height: PassHeight = Field(..., example="Ground Pass")
    angle: float = Field(..., example=0.25)
    duration: float = Field(..., example=1.35)
    body_part: Bodypart = Field(..., example="Right Foot")
    under_pressure: Literal[0,1] = Field(..., example=0)
    # log_velocity: float = Field(..., example=2.6)
    # angle_sin: float = Field(..., example=0.2474)
    # angle_cos: float = Field(..., example=0.9689)
    # start_distance_to_goal: float = Field(..., example=61.2)
    # end_distance_to_goal: float = Field(..., example=43.6)
    # progressive_distance: float = Field(..., example=17.6)
    # direction_to_goal: float = Field(..., example=-0.12)
    # direction_to_goal_cos: float = Field(..., example=0.9928)
    # duration_x_under_pressure: float = Field(..., example=0.0)
    # log_velocity_x_under_pressure: float = Field(..., example=0.0)
    # length_x_under_pressure: float = Field(..., example=0.0)
    # autoFE_f_0: float = Field(..., example=3.95)
    # autoFE_f_1: float = Field(..., example=1.35)
    # autoFE_f_2: float = Field(..., example=0.66)
    # autoFE_f_3: float = Field(..., example=1.35)
    # ofe_col_1: float = Field(..., example=0.14)