channels:
- conda-forge
dependencies:
- python=3.11.10
- pip
- pip:
  - mlflow==3.2.0
  - numpy==1.26.4
  - pandas==2.2.3
  - psutil==7.2.2
  - scikit-learn==1.5.0
  - scipy==1.14.1
  - xgboost==2.1.4
name: mlflow-env
